# coding: utf-8

"""
    RepositPower External

    Unofficial RepositPower External API This API is built by hand from the description at https://api.repositpower.com/docs/ It should not be mistaken for official in any way shape or form, it's simply my attempt to document the API and build some client libraries from that.  This API is demonstrably wrong around authentication - please read the official docco at the link above for accurate details. It will login, but all the login options are not captured - I wasn't clear how to write up both basic and token login being available on all URLs (ie. how to make auth an either/or rather than a both).  This API is also not completed yet. I've note tested a bunch of 200 responses, and some that I have don't have accurate enums in them because I don't know all the possible values. 

    OpenAPI spec version: 1.0.0
    Contact: kevin@littlejohn.id.au
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.default_api import DefaultApi


class TestDefaultApi(unittest.TestCase):
    """ DefaultApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.default_api.DefaultApi()

    def tearDown(self):
        pass

    def test_auth_login_get(self):
        """
        Test case for auth_login_get

        return access token upon successful basic auth
        """
        pass

    def test_auth_login_post(self):
        """
        Test case for auth_login_post

        return access token (session id) upon successful basic or html auth (use username/password, or use basic auth) 
        """
        pass

    def test_auth_logout_get(self):
        """
        Test case for auth_logout_get

        de-authenticate the token (always returns success)
        """
        pass

    def test_deployments_userkey_battery_capacity_get(self):
        """
        Test case for deployments_userkey_battery_capacity_get

        battery capacity in kWh
        """
        pass

    def test_deployments_userkey_battery_historical_soc_get(self):
        """
        Test case for deployments_userkey_battery_historical_soc_get

        state of charge of a battery in kWh
        """
        pass

    def test_deployments_userkey_components_get(self):
        """
        Test case for deployments_userkey_components_get

        installed components and their overall status
        """
        pass

    def test_deployments_userkey_cost_historical_get(self):
        """
        Test case for deployments_userkey_cost_historical_get

        energy cost in $
        """
        pass

    def test_deployments_userkey_generation_historical_p_get(self):
        """
        Test case for deployments_userkey_generation_historical_p_get

        solar generation data as negative real_power in kW
        """
        pass

    def test_deployments_userkey_gridcredits_historical_get(self):
        """
        Test case for deployments_userkey_gridcredits_historical_get

        earned gridcredits
        """
        pass

    def test_deployments_userkey_house_historical_get(self):
        """
        Test case for deployments_userkey_house_historical_get

        house consumption in kW
        """
        pass

    def test_deployments_userkey_inverter_historical_p_get(self):
        """
        Test case for deployments_userkey_inverter_historical_p_get

        the battery inverter data as real_power in kW
        """
        pass

    def test_deployments_userkey_meter_historical_p_get(self):
        """
        Test case for deployments_userkey_meter_historical_p_get

        real power measurements in kW at the grid connection
        """
        pass

    def test_userkeys_get(self):
        """
        Test case for userkeys_get

        all userkeys/battery system identifiers for the current user
        """
        pass


if __name__ == '__main__':
    unittest.main()
