# coding: utf-8

"""
    RepositPower External

    Unofficial RepositPower External API

    OpenAPI spec version: 1.0.0
    Contact: kevin@littlejohn.id.au
    Generated by: https://github.com/swagger-api/swagger-codegen.git

    Licensed under the Apache License, Version 2.0 (the "License");
    you may not use this file except in compliance with the License.
    You may obtain a copy of the License at

        http://www.apache.org/licenses/LICENSE-2.0

    Unless required by applicable law or agreed to in writing, software
    distributed under the License is distributed on an "AS IS" BASIS,
    WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
    See the License for the specific language governing permissions and
    limitations under the License.
"""

from __future__ import absolute_import

import os
import sys
import unittest

import swagger_client
from swagger_client.rest import ApiException
from swagger_client.apis.login_api import LoginApi


class TestLoginApi(unittest.TestCase):
    """ LoginApi unit test stubs """

    def setUp(self):
        self.api = swagger_client.apis.login_api.LoginApi()

    def tearDown(self):
        pass

    def test_auth_login_get(self):
        """
        Test case for auth_login_get

        return access token upon successful basic or html auth (use username/password, or use basic auth)
        """
        pass


if __name__ == '__main__':
    unittest.main()
